### ISSUE TITLE
Tests broken because of openupgradelib change

### ISSUE THREAD

**Issue by simahawk** [shopinvader/odoo-shopinvader#1111]
@sbidoul now that you've made possible to [autopublish openupgradelib on pypi ](https://github.com/OCA/openupgradelib/pull/243) (tnx!!) we have an issue here.

See https://github.com/shopinvader/odoo-shopinvader/pull/1110/checks?check_run_id=3675845704#step:4:68
```
     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hkf_whwc/openupgradelib_ac1fa9bcc23f4d429855baeb5a49e1db/setup.py", line 5, in <module>
        import openupgradelib
      File "/tmp/pip-install-hkf_whwc/openupgradelib_ac1fa9bcc23f4d429855baeb5a49e1db/openupgradelib/__init__.py", line 14, in <module>
        from importlib_metadata import version, PackageNotFoundError
    ModuleNotFoundError: No module named 'importlib_metadata'
```
AFAIS is needed only for py < 3.8 and here we still have 3.6. 

1. I don't think it should fail
2. I think we should move to py3.8 (which eliminates issue 1)
3. we should change requirements here to use openupgradelib from pypi instead of the github version

What do you think?

**Comment by sbidoul** [comment]
This should be fixed by now.

**Comment by simahawk** [comment]
@sbidoul thanks a lot, it works now!
