### ISSUE TITLE
[14.0] [BUG] `SHA hash` filename strategy gives in certain scenarios an error recomputing product --> `storage_file_path_uniq`

### ISSUE THREAD

**Issue by Mat-moran** [shopinvader/odoo-shopinvader#1176]
Hi,

did you suffer this strange error?. 
```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "storage_file_path_uniq"
DETAIL:  Key (relative_path, backend_id)=(aa/aa2a6813e7e888728dfea43f467f2beb7f0bc494, 2) already exists.
```
The error is a failed recompute job of the binded products to export to algolia. When I check the file, I do not have this record duplicated. This error should occur during the creation or assignation of the image to a backend not? why is this happening in a recompute job?.

The complete traceback pushing the `recompute` button in the shopinvader backend is `traceback 1` and pushing the button `Recompute shopinvader product`in the variant is `traceback 2`.

I will continue investigating,  if someone can give me some light I appreciate it. :smile: 

I am using the storage module with the S3 backend that is my  `backend_id=2`.

## Traceback 1
```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 36

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'shopinvader.variant(36,).images'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 209

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'storage.thumbnail(209,).url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 261

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'storage.file(261,).url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 261

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'storage.file(261,).backend_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/auto/addons/queue_job/controllers/main.py", line 73, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo/auto/addons/queue_job/controllers/main.py", line 32, in _try_perform_job
    job.perform()
  File "/opt/odoo/auto/addons/queue_job/job.py", line 506, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo/auto/addons/connector_search_engine/models/se_binding.py", line 146, in recompute_json
    index_record = mapper.map_record(binding).values()
  File "/opt/odoo/auto/addons/connector/components/mapper.py", line 1015, in values
    values = self._mapper._apply(self, options=options)
  File "/opt/odoo/auto/addons/connector_algolia/components/mapper.py", line 14, in _apply
    res = map_record._source.jsonify(self._json_parser)[0]
  File "/opt/odoo/auto/addons/base_jsonify/models/models.py", line 136, in jsonify
    self._jsonify_record(parsers[lang], record, json)
  File "/opt/odoo/auto/addons/base_jsonify/models/models.py", line 91, in _jsonify_record
    value = rec._jsonify_value(field, rec[field.name])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5667, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4062, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/auto/addons/shopinvader_image/models/shopinvader_image_mixin.py", line 33, in _compute_images
    self.filtered(lambda x: x._images_must_recompute())._compute_images_stored()
  File "/opt/odoo/auto/addons/shopinvader_image/models/shopinvader_image_mixin.py", line 39, in _compute_images_stored
    record.images_stored = record._get_image_data_for_record()
  File "/opt/odoo/auto/addons/shopinvader_image/models/shopinvader_image_mixin.py", line 86, in _get_image_data_for_record
    image_data[resize.key] = self._prepare_data_resize(
  File "/opt/odoo/auto/addons/shopinvader_image/models/shopinvader_image_mixin.py", line 103, in _prepare_data_resize
    return {"src": thumbnail.url, "alt": self.name, "tag": tag}
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4064, in _compute_field_value
    field.compute(self)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 555, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5667, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4062, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/auto/addons/storage_file/models/storage_file.py", line 146, in _compute_url
    record.url = record._get_url()
  File "/opt/odoo/auto/addons/storage_file/models/storage_file.py", line 150, in _get_url
    return self.backend_id._get_url_for_file(self)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2485, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 998, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3071, in _fetch_field
    self._read(fnames)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3089, in _read
    self.flush(fields, self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5476, in flush
    process(self.env[model_name], id_vals)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5431, in process
    recs._write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3755, in _write
    cr.execute(query, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "storage_file_path_uniq"
DETAIL:  Key (relative_path, backend_id)=(aa/aa2a6813e7e888728dfea43f467f2beb7f0bc494, 2) already exists.
```

## Traceback 2
```
2021-11-12 17:10:54,425 13016 ERROR shopinvader werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 807, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 110, in wrapper
    raise ValidationError(tr(key, 'sql_constraint') or inst.pgerror)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1479, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/http_routing/models/ir_http.py", line 508, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/custom/src/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/opt/odoo/custom/src/odoo/addons/http_routing/models/ir_http.py", line 598, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 745, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.exceptions.ValidationError: The private path must be uniq per backend - - -

```

**Comment by Mat-moran** [comment]
Hi, good morning.

I have identify the problem. 

Its occurs when you assign the same Image to different items. It is that done in pourpose, or is a bug in the code?

IMO there is a bug, images can be use in different products for example you can have a pack of  products that share images with the different products that are in the pack. 

what do you think?

**Comment by Mat-moran** [comment]
Hi,

its happend also in other scenarios not only assigning the same image to different product. For example I try to add 2 new resizes for my images, it works well for the first but give me the same error for the second one. 

__Changing the filename strategy__ in the backend from `SHA hash` to `Name and ID`  seems to solve the problem, so __should be something wrong with `SHA hash` filename strategy.__
