### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/var/lib/odoo/sessions'

### ISSUE THREAD

**Issue by meet-rizwan** [shopinvader/odoo-shopinvader#289]
hiii,
I am running docker odoo in my ubuntu 18 my following commands are below.
`docker run -d -v /data/postgres/giriraj:/var/lib/postgresql/data -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:10
`
i cloned odoo-shopinvader repository in my ubuntu machine at /docker/addons/odoo-shopinvader. and then ran 

` docker run -v /data/odoo/giriraj:/var/lib/odoo -v /docker/addons:/mnt/extra-addons  -p 8069:8069 -d --name odoo --link db:db -t odoo:10.0
`
and my odoo-container logs are below

```
2019-03-31 07:27:52,284 1 INFO ? odoo: Odoo version 10.0-20190128

2019-03-31 07:27:52,284 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf

2019-03-31 07:27:52,285 1 INFO ? odoo: addons paths: [u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packages/odoo/addons']

2019-03-31 07:27:52,285 1 INFO ? odoo: database: odoo@172.17.0.3:5432

2019-03-31 07:27:52,308 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on ce829d1adfb6:8069

2019-03-31 07:28:02,117 1 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf

2019-03-31 07:28:02,583 1 INFO ? odoo.http: HTTP Configuring static files

2019-03-31 07:28:02,590 1 INFO ? werkzeug: 47.247.222.34 - - [31/Mar/2019 07:28:02] "GET / HTTP/1.1" 500 -

2019-03-31 07:28:02,599 1 ERROR ? werkzeug: Error on request:

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi

    execute(self.server.app)

  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute

    application_iter = app(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 247, in app

    return self.app(e, s)

  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application

    return application_unproxied(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied

    result = handler(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1326, in __call__

    return self.dispatch(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1300, in __call__

    return self.app(environ, start_wrapped)

  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__

    return self.app(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1463, in dispatch

    explicit_session = self.setup_session(httprequest)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1360, in setup_session

    session_gc(self.session_store)

  File "/usr/lib/python2.7/dist-packages/odoo/tools/func.py", line 23, in __get__

    value = self.fget(obj)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1311, in session_store

    path = odoo.tools.config.session_dir

  File "/usr/lib/python2.7/dist-packages/odoo/tools/config.py", line 604, in session_dir

    os.makedirs(d, 0700)

  File "/usr/lib/python2.7/os.py", line 157, in makedirs

    mkdir(name, mode)

OSError: [Errno 13] Permission denied: '/var/lib/odoo/sessions'

2019-03-31 07:28:03,055 1 INFO ? werkzeug: 47.247.222.34 - - [31/Mar/2019 07:28:03] "GET /favicon.ico HTTP/1.1" 500 -

2019-03-31 07:28:03,063 1 ERROR ? werkzeug: Error on request:

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi

    execute(self.server.app)

  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute

    application_iter = app(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 247, in app

    return self.app(e, s)

  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application

    return application_unproxied(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied

    result = handler(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1326, in __call__

    return self.dispatch(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1300, in __call__

    return self.app(environ, start_wrapped)

  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__

    return self.app(environ, start_response)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1463, in dispatch

    explicit_session = self.setup_session(httprequest)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1360, in setup_session

    session_gc(self.session_store)

  File "/usr/lib/python2.7/dist-packages/odoo/tools/func.py", line 23, in __get__

    value = self.fget(obj)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1311, in session_store

    path = odoo.tools.config.session_dir

  File "/usr/lib/python2.7/dist-packages/odoo/tools/config.py", line 604, in session_dir

    os.makedirs(d, 0700)

  File "/usr/lib/python2.7/os.py", line 157, in makedirs

    mkdir(name, mode)

OSError: [Errno 13] Permission denied: '/var/lib/odoo/sessions'


```

**Comment by simahawk** [comment]
this issue is pretty old and in any case seems unrelated to shopinvader features.
