### ISSUE TITLE
[12.0] Error when upgrading the module 'shopinvader'

### ISSUE THREAD

**Issue by JordiBForgeFlow** [shopinvader/odoo-shopinvader#538]
When we upgrade 'shopinvader' we get this error. Not sure why..

`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3844, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3782, in _load_records_write
    self.write(values)
  File "/opt/odoo/auto/addons/shopinvader/models/res_partner.py", line 93, in write
    super(ResPartner, self).write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 569, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 321, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/auto/addons/mail/models/mail_activity.py", line 588, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/auto/addons/component_event/models/base.py", line 105, in write
    self._event('on_record_write').notify(record, fields=fields)
  File "/opt/odoo/auto/addons/component_event/components/event.py", line 190, in notify
    event(*args, **kwargs)
  File "/opt/odoo/auto/addons/component_event/components/event.py", line 160, in func_wrapper
    return func(*args, **kwargs)
  File "/opt/odoo/auto/addons/shopinvader_locomotive/component/event_listeners.py", line 48, in on_record_write
    for binding in record._get_binding_to_export():
AttributeError: 'res.partner' object has no attribute '_get_binding_to_export'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 622, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3844, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3782, in _load_records_write
    self.write(values)
  File "/opt/odoo/auto/addons/shopinvader/models/res_partner.py", line 93, in write
    super(ResPartner, self).write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 569, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 321, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/auto/addons/mail/models/mail_activity.py", line 588, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/auto/addons/component_event/models/base.py", line 105, in write
    self._event('on_record_write').notify(record, fields=fields)
  File "/opt/odoo/auto/addons/component_event/components/event.py", line 190, in notify
    event(*args, **kwargs)
  File "/opt/odoo/auto/addons/component_event/components/event.py", line 160, in func_wrapper
    return func(*args, **kwargs)
  File "/opt/odoo/auto/addons/shopinvader_locomotive/component/event_listeners.py", line 48, in on_record_write
    for binding in record._get_binding_to_export():
odoo.tools.convert.ParseError: "'res.partner' object has no attribute '_get_binding_to_export'" while parsing /opt/odoo/auto/addons/shopinvader/data/res_partner.xml:4, near
<record id="anonymous" model="res.partner">
        <field name="name">Anonymous</field>
    </record>`

**Comment by lmignon** [comment]
@JordiBForgeFlow Thank you for the report. I've never encountered this error before... looks very strange since the method is defined into the shopinvader_locomotive addon. Are you in the upgrade process of the shopinvader addon at this stage of your update? Looks like the event_listener in shopinvader_locomotive is already registered but the addon not yet loaded into the registry.
